apiVersion: apps/v1
kind: Deployment
metadata:
     name: mywebapp
spec:
     selector:
          matchLabels:
                app: frontend
     template:
          metadata:
               name: abc
               labels:
                   app: frontend
          spec:
               containers:
                   - name: pqr
                     image: rohir/myapp
                     ports:
                          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
     name: webapp
spec:
    type: NodePort
    ports:
        - nodePort: 30080
          port: 80
          targetPort: 80
    selector:
         app: frontend

